project:
  type: website

website:
  theme: lumen
  navbar:
    left:
      - text: About You
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd


