project:
  type: website

website:
  title: "Ryan Martin's Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About You
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: lumen

