---
title: "Backround and Interests"
---

## About Me

I was born and raised in Chapel Hill, North Carolina. and come fromy a family of six. My mother is from Ireland, and my father is from South Africa. I have one brother and two sisters - my brother and sister are from England, and my other sister is also from Chapel Hill. 

I am a highly motivated and detail-oriented mathematics graduate with a passion for solving complex problems and uncovering actionable insights through data analysis. My background includes advanced calculus, statistical modeling, and research, where I have consistently delivered impactful results in both academic and professional settings.

I am skilled in leveraging technical tools such as MATLAB and Python to craft innovative solutions to challenging problems. My expertise extends to Microsoft Excel, research and data analysis, statistics and probability, and R scripting for statistical computing.

Currently, I am pursuing a Master of Science in Applied Business Analytics at Boston University, building on my Bachelor of Science in Mathematics from Southern New Hampshire University and a Bachelor of Arts in History from the University of North Carolina at Chapel Hill.

## Career Goals

I am excited to contribute to collaborative, data-driven environments where my analytical expertise can drive organizational success and growth. My goal is to apply my skills in mathematics and data analytics to solve real-world problems and support decision-making processes.

## Interests

Outside of my professional pursuits, I am an avid long-distance runner and active CrossFit member. I enjoy collecting comics and engaging in puzzle and logic games, which reflect my creativity and critical thinking skills.

Feel free to explore the other sections of my portfolio to learn more about my projects, achievements, and how to get in touch.

